### ISSUE TITLE
Support setting Pod tolerations in spec.nodeAssignments

### ISSUE THREAD

**Issue by zbialik** [SolaceProducts/pubsubplus-kubernetes-quickstart#73]
We use taints on all of our k8s `Nodes` so we can't use this operator until we can set `tolerations` for the `StatefulSets`/`Pods` created.

**Comment by bczoma** [comment]
Hi @zbialik , thank you, acknowledged. This is planned for the next release although we don't have a date for it yet.

**Comment by LewisKSaint** [comment]
Hello @zbialik, this has been added to the current release of the Operator.
