### ISSUE TITLE
Cluster level access

### ISSUE THREAD

**Issue by Praveenk8051** [SolaceProducts/pubsubplus-kubernetes-quickstart#80]
Im trying to deploy pubsubsubplus on k8s Cluster. Looks like the image or the deployment tries to ask for cluster level access.

Is it possible to tune the parameters to work at Namespace level instead of Cluster level ? Does it involve change in the source code ?

**Comment by sebay** [comment]
@Praveenk8051 you need to set:
```
        - name: WATCH_NAMESPACE
          value: "{{ .Values.operatorNamespace }}"
```
Also you can reduce all ClusterRole to Role in RBACs if you are working on one namespace only.
